### ISSUE TITLE
Do you plan to release the 2017 dataset alignments? thanks

### ISSUE THREAD

**Issue by miguelballesteros** [Oneplus/tamr#2]

**Comment by miguelballesteros** [comment]
thanks!

**Comment by Oneplus** [comment]
@miguelballesteros I've just committed the alignment for ldc2017t10. it's here: https://github.com/Oneplus/tamr/tree/master/release/ldc2017t10. please check. 

I will close this issue. if there is any problem regarding the alignment, please open another issue and let know.
